### ISSUE TITLE
Cslolmanager request!

### ISSUE THREAD

**Issue by MejaiReponse** [Morilli/riot-manifests#4]
Hi, i want just for there to be more security to mod files!

I want the options “export mod”, and “edit mod” to be removed. And for there to be no option to “import mod” but rather i can put the files inside the program somehow so it comes pre-installed with no way to find the mod files within the program folders. (Maybe in the .exe application?)

And it saves the mod files to a folder called “installed” and i want that removed too.

please let me know if you can do this! i'm willing to pay money if you can do the changes i want!

**Comment by Morilli** [comment]
First of all, this isn't the correct repository, so I'm going to close this issue here.

Also, this doesn't sound like a very useful feature request; it seems like you're trying to prevent people from accessing the mods they have installed, which is kinda contradictory to the idea of a mod manager.
